// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stuart_Hopwood_Photography_API.Data;

namespace Stuart_Hopwood_Photography_API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190610213838_modified-authtoken-table")]
    partial class modifiedauthtokentable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Stuart_Hopwood_Photography_API.Entities.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Issued");

                    b.Property<string>("IssuedUtc");

                    b.Property<string>("Token")
                        .HasMaxLength(2000);

                    b.Property<string>("UserKey")
                        .HasMaxLength(255);

                    b.Property<string>("access_token")
                        .HasMaxLength(2000);

                    b.Property<int>("expires_in");

                    b.Property<string>("id_token");

                    b.Property<string>("refresh_token")
                        .HasMaxLength(1000);

                    b.Property<string>("scope")
                        .HasMaxLength(1000);

                    b.Property<string>("token_type")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("OAuthToken");
                });

            modelBuilder.Entity("Stuart_Hopwood_Photography_API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
